Update test-all-your-base.bats
exercism/awk pull request #261
Opened 2024-05-23 20:58 UTC by Vincent-de-Comarmond

0 should not be converted to the empty string when converting between bases. 0 should remain 0.

2024-05-23 21:28 UTC, glennj commented
@IsaacG do you remember why the output is empty when the input digits are all zeroes? This is from #63

2024-05-23 21:35 UTC, glennj commented
@Vincent-de-Comarmond it's not enough to alter the tests: you have to make sure the example solution passes:

* run `bin/validate_one_exercise exercises/practice/all-your-base`
* edit `exercises/practice/all-your-base/.meta/example.awk`
* repeat until the tests pass.

2024-05-23 22:23 UTC, Vincent-de-Comarmond commented
@glennj  - Updated example solution as asked

2024-05-24 08:48 UTC, IsaacG commented
> @IsaacG do you remember why the output is empty when the input digits are all zeroes? This is from #63

No. Probably an oversight. Though I would have expected the tests to be auto generated from the spec.

2024-05-24 12:12 UTC, glennj requested changes

2024-05-24 12:12 UTC, glennj commented on exercises/practice/all-your-base/test-all-your-base.bats
> +    assert_output "0" # 0 is 0 in any base
Can you remove the comments please

2024-05-24 21:14 UTC, glennj approved these changes

2024-05-24 21:16 UTC, merged

2024-05-24 21:16 UTC, glennj commented
Thanks for working to fix this!